// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALk_clInwQV5swvEv7NC8eguFA-1sBNfM',
    appId: '1:789792800112:web:119f83552f8a7adc1663b5',
    messagingSenderId: '789792800112',
    projectId: 'flash-chat-e1996',
    authDomain: 'flash-chat-e1996.firebaseapp.com',
    storageBucket: 'flash-chat-e1996.appspot.com',
    measurementId: 'G-8E94GZKZ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlZD0QDceNXfW0A6mB6SgQRU2IyJLV0Ds',
    appId: '1:789792800112:android:dc4a82cf425ca1411663b5',
    messagingSenderId: '789792800112',
    projectId: 'flash-chat-e1996',
    storageBucket: 'flash-chat-e1996.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD33_G-Y-PqLI4KKmP5GIr_MUT_szO9xJs',
    appId: '1:789792800112:ios:b930561773ecd3d21663b5',
    messagingSenderId: '789792800112',
    projectId: 'flash-chat-e1996',
    storageBucket: 'flash-chat-e1996.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD33_G-Y-PqLI4KKmP5GIr_MUT_szO9xJs',
    appId: '1:789792800112:ios:b930561773ecd3d21663b5',
    messagingSenderId: '789792800112',
    projectId: 'flash-chat-e1996',
    storageBucket: 'flash-chat-e1996.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );
}
